### DISCUSSION TITLE
What's the best way to set the Color of the math shortcode dependent on dark or light mode...

### DISCUSSION THREAD

**Discussion by cnichte** [gethyas/hyas#441] [General]
Hi, what's the best way to set the Color of the `math shortcode` dependent on dark bzw light mode? Perhaps that should be done automatically in the shortcode itself?

```
{{< math color=white >}}${(x+y)}^2${{< /math >}}
```

any recommendations are welcome :-)

**Comment by h-enk** [comment]
I'd say don't set the color, but add some SCSS:

```scss
@include color-mode(dark) {
  .math-inline img,
  .math-block img {
    filter: invert(1);
  }
}
```

I will add this to `docs-core`
