### DISCUSSION TITLE
Best practice using external  js modules in hyas, installed from npm

### DISCUSSION THREAD

**Discussion by cnichte** [gethyas/hyas#442] [General]
I am not quite sure how to integrate an external javascript in Hyas in the best way. In my case I have 

https://github.com/banthagroup/fslightbox

installed, like so

```
npm install fslightbox
```

Now it is in the directory `/node_modules/fslightbox/index.js` (hooray) But how do I proceed from there?

As always, I'm happy about any tips :-)

**Comment by h-enk** [comment]
If it's a small script (like `fslightbox.js`), add it to `app.js` using `custom.js`.

Create `assets/js/custom.js` and require fslightbox.js:

```js
// Put your custom JS code here

// require fslightbox.js
require('fslightbox')
```

Temporarily required extra step: exclude `js/custom.js` in `config/_default/module.toml`:

```toml
[[mounts]]
  source = "node_modules/@hyas/doks-core/assets"
  target = "assets"
  excludeFiles = ["scss/common/_variables-custom.scss", "scss/common/_custom.scss", "js/custom.js"]
```
