### DISCUSSION TITLE
Image cropped on the sides

### DISCUSSION THREAD

**Discussion by dend** [gethyas/hyas#459] [Q&A] [answered]
I have the following configuration in my `params.toml`:

```toml
# Images (@hyas/images)
[hyas_images]
  [hyas_images.landscape]
    normalize = "1600x900" # "1600x900" (default)
    lqip = "16x9" # "16x9" (default)
    widths = [640, 768, 1024, 1366, 1600, 1920]
    process = "resize 1600x"
  [hyas_images.portrait]
    normalize = "765x1360" # "900x1600" (default)
    lqip = "9x16" # "9x16" (default)
    widths = [480, 640, 800, 1024]
  [hyas_images.defaults]
    decoding = "async" # sync, async, or auto (default)
    fetchpriority = "auto" # high, low, or auto (default) 
    loading = "lazy" # eager or lazy (default)
    widths = [640, 768, 1024, 1366, 1600, 1920] # [640, 768, 1024, 1366, 1600, 1920] for example
    sizes = "auto" # 100vw (default), 75vw, or auto for example
    #process = "fill 2100x900" # "fill 1600x900" or "fill 2100x900" for example
    lqip = "16x webp q20" # "16x webp q20" or "21x webp q20" for example
```

The image that ends up rendered on the page is cropped from right and left:

![Cropped screenshot, as seen in Hyas-powered website](https://github.com/gethyas/hyas/assets/1389609/a269ad79-b8c3-4226-88d2-47243c405478)

Here is what the image should look like:

![Uncropped screenshot](https://github.com/gethyas/hyas/assets/1389609/7dc55e48-ed78-4dfd-99c2-787974bf5d1d)

What is the best way to ensure that the image is correctly shown?
