### DISCUSSION TITLE
Multilingual Support Documentation Request

### DISCUSSION THREAD

**Discussion by jason810496** [gethyas/hyas#482] [General]
Thanks for creating this fantastic theme!

When it comes to configuring multilingual support, the documentation on internationalization lacks guides: 
[Internationalization Documentation](https://docs.gethyas.com/guides/internationalization/).

I've tried configuring the following settings:

- `config/_default/params.toml`
```toml
# Multilingual
multilingualMode = true # false (default) or true
multilingualModeToggler = true # true (default) or false
showMissingLanguages = true # whether or not to show untranslated languages in the language menu; true (default) or false
```

- Added `config/_default/menus/menus.zh.toml` for Mandarin.
- Added `config/_default/languages.toml` for Mandarin.

However, the top-left language toggle button doesn't function as expected. 
It neither opens the language selection dropdown nor toggles to another language.

However, directly changing the base URL to `/zh/xxx` does switch to Mandarin.
