### DISCUSSION TITLE
How to import Hugo modules

### DISCUSSION THREAD

**Discussion by percula** [gethyas/hyas#500] [Q&A]
I'm trying to import a Hugo module to add icon shortcode support. However, when I follow the instructions [here](https://icons.hugomods.com/docs/installation/), it seems to replace the Doks theme. Is there a better way to import non-theme modules?

**Comment by h-enk** [comment]
Though it is possible to use Hugo Modules next to npm, it is not recommended. Keeping all your project dependencies in one place — id est in `package.json` — is easier/ more convenient. For more background, see [Dependencies](https://docs.thulite.io/concepts/dependencies/).

Doks comes with an [icon shortcode](https://getdoks.org/docs/basics/shortcodes/#tabler-icons) that you can use with any icon set.

For example, to use [Bootstrap Icons](https://icons.getbootstrap.com/):

1. Install the icon set:

    ```bash
    npm i -D bootstrap-icons
    ```

2. Add to `config/_default/module.toml` (after line 27):

    ```toml
    [[mounts]]
      source = "node_modules/bootstrap-icons/icons"
      target = "assets/svgs/bootstrap-icons"
    ```

3. Update `config/_default/params.toml` (line 114..116):

    ```toml
    # Inline SVG (@thulite/inline-svg)
    [inline_svg]
      iconSetDir = "bootstrap-icons" # "tabler-icons" (default)
    ```

Use the shortcode in your markdown files like so:

```md
{{< inline-svg "1-circle" >}}
```

You can also specify [SVG attributes](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute), for example:

```md
{{< inline-svg src="2-circle" fill="#ee52b7" height="2rem" width="2rem" class="svg-inline-custom" >}}
```

![2024-12-03_08-22-22](https://github.com/user-attachments/assets/143f1705-0219-4e70-93cc-aed0cfb45f4a)
