### DISCUSSION TITLE
[HowTo?] Can I create an image map in Hugo/Thulite?

### DISCUSSION THREAD

**Discussion by Squadz** [gethyas/hyas#505] [General]
Hi Everyone,

I want to direct users to different destinations based on the coordinates they click on within an image. Ideally, the image would be a diagram generated by Kroki (e.g., https://getdoks.org/docs/built-ins/diagrams/).

After some research, it seems this isn't possible with Markdown. Is there a way to use HTML as content in Thulite instead of Markdown?

Thanks in advance for your help!

**Comment by h-enk** [comment]
In `config/_default/markup.toml`, set `goldmark.renderer.unsafe` to `true` (Thulite default):

```toml
defaultMarkdownHandler = "goldmark"

[goldmark]
  [goldmark.renderer]
    unsafe = true
```

Now, you can use HTML in Markdown — see also the [Hugo docs](https://gohugo.io/getting-started/configuration-markup/#rendererunsafe)
